<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create' => '创建',
    'Update' => '更新',
    'Create {modelClass}' => '创建{modelClass}',
    'Update {modelClass}: ' => '更新{modelClass}:',
    'Carousel' => '幻灯片',
    'Nav' => '导航',
    'Navs' => '导航',
    'Account details' => '账户',
    'Profile details' => '信息',
    'Assignments' => '指派',
    'Block' => '封禁',
    'UnBlock' => '解禁',
    'Level' => '级别',
    'Category' => '分类',
    'You can assign multiple roles or permissions to user by using the form below' => '您可以使用下面的表单给用户分配多个角色或权限',
    '文章栏目' => 'article category'
];